# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: 'CI - node tests'
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 12.x]

    # Service containers to run with `runner-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432




    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}


        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}


      - name: Install npm dependencies
        run: npm ci


      - name: Run build - Connect to database and initialize it
        run: npm run build --if-present
        env:
          DB_TEST_URL: postgres://postgres:postgres@localhost:5432/postgres
          NODE_ENV: development


      - name: run server tests
        run: npm run test_server
        env:
          DB_TEST_URL: postgres://postgres:postgres@localhost:5432/postgres


      - name: run database tests
        run: npm run test_db
        env:
          DB_TEST_URL: postgres://postgres:postgres@localhost:5432/postgres
